### ISSUE TITLE
How to customize SCSS variables for GitHub Pages using `remote_theme: ` `minima`?

### ISSUE THREAD

**Issue by vadimkantorov** [jekyll/minima#769]
If I place `assets/main.scss` as recommended in https://github.com/jekyll/minima/tree/v2.5.1?tab=readme-ov-file#customization:

```scss
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@import "minima";

$on-palm:          6000px !important;
```

Jekyll fails to build the site as it cannot discover `minima` as it is extracted in some temporary path.

How do I properly override some SCSS variables, e.g. constants in https://github.com/jekyll/minima/blob/master/_sass/minima/initialize.scss for use with GitHub Pages and not having to fork the entire `minima` repo?

Thanks!

---

Logs from GitHub Pages / GitHub Actions:
```
2023-12-19T15:19:21.9014912Z ##[command]/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv109_c9d33e --label cfe859 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/notionfun/notionfun":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.9
2023-12-19T15:19:23.1613362Z To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
2023-12-19T15:19:24.5882682Z [31m  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main.scss':[0m
2023-12-19T15:19:24.5886960Z [31m                    File to import not found or unreadable: minima. Load paths: /github/workspace/_sass /usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_sass /tmp/jekyll-remote-theme-20231219-7-1kske1l/_sass on line 1[0m
2023-12-19T15:19:24.5890226Z /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': File to import not found or unreadable: minima. (Jekyll::Converters::Scss::SyntaxError)
2023-12-19T15:19:24.5891815Z Load paths:
2023-12-19T15:19:24.5892149Z   /github/workspace/_sass
2023-12-19T15:19:24.5892781Z   /usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_sass
2023-12-19T15:19:24.5893649Z   /tmp/jekyll-remote-theme-20231219-7-1kske1l/_sass on line 1
2023-12-19T15:19:24.5894880Z 	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:118:in `convert'
2023-12-19T15:19:24.5896290Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:101:in `block in convert'
2023-12-19T15:19:24.5897498Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `each'
2023-12-19T15:19:24.5898617Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `reduce'
2023-12-19T15:19:24.5899752Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `convert'
2023-12-19T15:19:24.5918307Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:83:in `render_document'
2023-12-19T15:19:24.5919778Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:62:in `run'
2023-12-19T15:19:24.5921906Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:479:in `render_regenerated'
2023-12-19T15:19:24.5923374Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:472:in `block in render_pages'
2023-12-19T15:19:24.5924555Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `each'
2023-12-19T15:19:24.5925672Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `render_pages'
2023-12-19T15:19:24.5926785Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:192:in `render'
2023-12-19T15:19:24.5927873Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:71:in `process'
2023-12-19T15:19:24.5929028Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
2023-12-19T15:19:24.5930236Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
2023-12-19T15:19:24.5931443Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
2023-12-19T15:19:24.5932874Z 	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
2023-12-19T15:19:24.5934374Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
2023-12-19T15:19:24.5935651Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
2023-12-19T15:19:24.5936884Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
2023-12-19T15:19:24.5938088Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
2023-12-19T15:19:24.5939281Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
2023-12-19T15:19:24.5940468Z 	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
2023-12-19T15:19:24.5941460Z 	from /usr/local/bundle/bin/github-pages:23:in `load'
2023-12-19T15:19:24.5942201Z 	from /usr/local/bundle/bin/github-pages:23:in `<main>'
2023-12-19T15:19:24.5943044Z (sass):1: File to import not found or unreadable: minima. (Sass::SyntaxError)
2023-12-19T15:19:24.5943750Z Load paths:
2023-12-19T15:19:24.5944086Z   /github/workspace/_sass
2023-12-19T15:19:24.5944667Z   /usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_sass
2023-12-19T15:19:24.5945431Z   /tmp/jekyll-remote-theme-20231219-7-1kske1l/_sass
2023-12-19T15:19:24.5946496Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/import_node.rb:67:in `rescue in import'
2023-12-19T15:19:24.5947741Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/import_node.rb:44:in `import'
2023-12-19T15:19:24.5948983Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/import_node.rb:28:in `imported_file'
2023-12-19T15:19:24.5950268Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/import_node.rb:37:in `css_import?'
2023-12-19T15:19:24.5951590Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:310:in `visit_import'
2023-12-19T15:19:24.5952891Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
2023-12-19T15:19:24.5954227Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
2023-12-19T15:19:24.5955789Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
2023-12-19T15:19:24.5956930Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
2023-12-19T15:19:24.5958019Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
2023-12-19T15:19:24.5959194Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
2023-12-19T15:19:24.5960577Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
2023-12-19T15:19:24.5961909Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'
2023-12-19T15:19:24.5963176Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
2023-12-19T15:19:24.5964840Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
2023-12-19T15:19:24.5988694Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
2023-12-19T15:19:24.5990771Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
2023-12-19T15:19:24.5992179Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
2023-12-19T15:19:24.5993534Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
2023-12-19T15:19:24.5994816Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
2023-12-19T15:19:24.5996206Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:157:in `visit'
2023-12-19T15:19:24.5997452Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
2023-12-19T15:19:24.5998666Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/root_node.rb:36:in `css_tree'
2023-12-19T15:19:24.5999850Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/root_node.rb:20:in `render'
2023-12-19T15:19:24.6000955Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
2023-12-19T15:19:24.6001921Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass.rb:57:in `compile'
2023-12-19T15:19:24.6003175Z 	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
2023-12-19T15:19:24.6004582Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:101:in `block in convert'
2023-12-19T15:19:24.6006146Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `each'
2023-12-19T15:19:24.6009811Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `reduce'
2023-12-19T15:19:24.6018281Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `convert'
2023-12-19T15:19:24.6019630Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:83:in `render_document'
2023-12-19T15:19:24.6020828Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:62:in `run'
2023-12-19T15:19:24.6022030Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:479:in `render_regenerated'
2023-12-19T15:19:24.6023481Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:472:in `block in render_pages'
2023-12-19T15:19:24.6024658Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `each'
2023-12-19T15:19:24.6025753Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `render_pages'
2023-12-19T15:19:24.6026884Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:192:in `render'
2023-12-19T15:19:24.6027971Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:71:in `process'
2023-12-19T15:19:24.6029108Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
2023-12-19T15:19:24.6030309Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
2023-12-19T15:19:24.6031533Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
2023-12-19T15:19:24.6035626Z 	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
2023-12-19T15:19:24.6037220Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
2023-12-19T15:19:24.6038521Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
2023-12-19T15:19:24.6039911Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
2023-12-19T15:19:24.6041112Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
2023-12-19T15:19:24.6042259Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
2023-12-19T15:19:24.6043508Z 	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
2023-12-19T15:19:24.6044488Z 	from /usr/local/bundle/bin/github-pages:23:in `load'
2023-12-19T15:19:24.6045243Z 	from /usr/local/bundle/bin/github-pages:23:in `<main>'
2023-12-19T15:19:24.6047123Z /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/import_node.rb:65:in `import': File to import not found or unreadable: minima. (Sass::SyntaxError)
2023-12-19T15:19:24.6048458Z Load paths:
2023-12-19T15:19:24.6048775Z   /github/workspace/_sass
2023-12-19T15:19:24.6049382Z   /usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_sass
2023-12-19T15:19:24.6050218Z   /tmp/jekyll-remote-theme-20231219-7-1kske1l/_sass
2023-12-19T15:19:24.6051240Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/import_node.rb:28:in `imported_file'
2023-12-19T15:19:24.6052521Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/import_node.rb:37:in `css_import?'
2023-12-19T15:19:24.6053856Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:310:in `visit_import'
2023-12-19T15:19:24.6055134Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
2023-12-19T15:19:24.6056468Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
2023-12-19T15:19:24.6057773Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
2023-12-19T15:19:24.6058906Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
2023-12-19T15:19:24.6059995Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
2023-12-19T15:19:24.6061165Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
2023-12-19T15:19:24.6062562Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
2023-12-19T15:19:24.6063874Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'
2023-12-19T15:19:24.6065134Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
2023-12-19T15:19:24.6066613Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
2023-12-19T15:19:24.6068139Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
2023-12-19T15:19:24.6069611Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
2023-12-19T15:19:24.6071004Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
2023-12-19T15:19:24.6072372Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
2023-12-19T15:19:24.6073634Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
2023-12-19T15:19:24.6074861Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:157:in `visit'
2023-12-19T15:19:24.6076402Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
2023-12-19T15:19:24.6077601Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/root_node.rb:36:in `css_tree'
2023-12-19T15:19:24.6078764Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/tree/root_node.rb:20:in `render'
2023-12-19T15:19:24.6079867Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
2023-12-19T15:19:24.6080865Z 	from /usr/local/bundle/gems/sass-3.7.4/lib/sass.rb:57:in `compile'
2023-12-19T15:19:24.6082102Z 	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
2023-12-19T15:19:24.6083512Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:101:in `block in convert'
2023-12-19T15:19:24.6084712Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `each'
2023-12-19T15:19:24.6086618Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `reduce'
2023-12-19T15:19:24.6087770Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `convert'
2023-12-19T15:19:24.6088968Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:83:in `render_document'
2023-12-19T15:19:24.6090122Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:62:in `run'
2023-12-19T15:19:24.6091489Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:479:in `render_regenerated'
2023-12-19T15:19:24.6092904Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:472:in `block in render_pages'
2023-12-19T15:19:24.6094079Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `each'
2023-12-19T15:19:24.6095178Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `render_pages'
2023-12-19T15:19:24.6096305Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:192:in `render'
2023-12-19T15:19:24.6097394Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:71:in `process'
2023-12-19T15:19:24.6098529Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
2023-12-19T15:19:24.6099728Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
2023-12-19T15:19:24.6100946Z 	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
2023-12-19T15:19:24.6102360Z 	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
2023-12-19T15:19:24.6103865Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
2023-12-19T15:19:24.6105158Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
2023-12-19T15:19:24.6106382Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
2023-12-19T15:19:24.6107568Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
2023-12-19T15:19:24.6108708Z 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
2023-12-19T15:19:24.6109901Z 	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
2023-12-19T15:19:24.6110902Z 	from /usr/local/bundle/bin/github-pages:23:in `load'
2023-12-19T15:19:24.6111651Z 	from /usr/local/bundle/bin/github-pages:23:in `<main>'
2023-12-19T15:19:24.6197456Z ##[error] Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v228 GitHub Pages: jekyll v3.9.3 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings Requiring: jekyll-remote-theme GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... Theme: jekyll/minima Theme source: /tmp/jekyll-remote-theme-20231219-7-1kske1l Remote Theme: Using theme jekyll/minima Remote Theme: Downloading https://codeload.github.com/jekyll/minima/zip/HEAD to /tmp/jekyll-remote-theme-20231219-7-1koktji.zip Remote Theme: Unzipping /tmp/jekyll-remote-theme-20231219-7-1koktji.zip to /tmp/jekyll-remote-theme-20231219-7-1kske1l Requiring: jekyll-feed Requiring: jekyll-seo-tag Generating: JekyllOptionalFrontMatter::Generator finished in 0.034024479 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.001877543 seconds. Generating: Jekyll::Paginate::Pagination finished in 5.5e-06 seconds. GitHub Metadata: Generating for vadimkantorov/notionfun GitHub Metadata: Calling @client.pages("vadimkantorov/notionfun", {}) Generating: JekyllRelativeLinks::Generator finished in 0.424598712 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.002933367 seconds. Requiring: commonmarker Generating: JekyllTitlesFromHeadings::Generator finished in 0.005264121 seconds. Rendering: index.md Pre-Render Hooks: index.md Rendering Liquid: index.md Rendering Markup: index.md Rendering Layout: index.md Layout source: theme Rendering: assets/main.scss Pre-Render Hooks: assets/main.scss Rendering Markup: assets/main.scss github-pages 228 | Error: File to import not found or unreadable: minima. Load paths: /github/workspace/_sass /usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_sass /tmp/jekyll-remote-theme-20231219-7-1kske1l/_sass on line 1 Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20231219-7-1kske1l 
```

**Comment by osbre** [comment]
I'd recommend using 

```ruby
gem "minima", :github => 'jekyll/minima'
```

in your `Gemfile` instead of `remote_theme`

**Comment by vadimkantorov** [comment]
when using jekyll/minima in GH Pages, I don't have a `Gemfile` or am I missing something?

**Comment by revolter** [comment]
> I'd recommend using
> 
> ```ruby
> gem "minima", :github => 'jekyll/minima'
> ```
> 
> in your `Gemfile` instead of `remote_theme` as a solution.

Why?

**Comment by osbre** [comment]
@revolter requires one less gem (built-in solution)

**Comment by revolter** [comment]
@osbre, true, although it causes issues in some cases: https://github.com/rubygems/rubygems/issues/7652#issuecomment-2106070006
